---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r}
if(!file.exists("activity.zip"))
  download.file("https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip", "activity.zip")

if (!file.exists("activity.csv"))
  unzip("activity.zip")

data <- read.csv("activity.csv")
```


## What is mean total number of steps taken per day?
```{r} 
stepsByDay <- aggregate(data["steps"], by=data["date"], sum)

meanSteps <- format(mean(stepsByDay$steps, na.rm="TRUE"), scientific = FALSE)

medianSteps <- median(stepsByDay$steps, na.rm=TRUE)

hist(stepsByDay$steps,
     xlab = "Total number of steps taken each day",
     ylab = "Count",
     main = "Histogram - total number of steps taken each",
     col = 4)
```

The mean total number of steps taken each day is `r meanSteps`, and the median number of steps taken each day is `r medianSteps`.


## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
